### ISSUE TITLE
IndexError: string index out of range  when del_attr(...)

### ISSUE THREAD

**Issue by erik78se** [towalink/wgconfig#4]
If I run this code on a configfile - an unhandled exception occurs.

Traceback (most recent call last):
  File "/home/erik/dwellir/wireguard-sub/wgconf.py", line 30, in <module>
    mana()
  File "/home/erik/dwellir/wireguard-sub/wgconf.py", line 23, in mana
    wc.del_attr(None,'ListenPort')
  File "/home/erik/dwellir/wireguard-sub/venv/lib/python3.10/site-packages/wgconfig/__init__.py", line 248, in del_attr
    if self.lines[i][0] == '#':
IndexError: string index out of range

It would be good to handle that exception and let a user know to have remove_leading_comments=False 

import wgconfig

def removeAttr():
    wc = wgconfig.WGConfig('./wg0.conf')
    wc.read_file()
    print(wc.interface)
    # wc.del_attr(None,'PrivateKey')
    wc.del_attr(None,'ListenPort', remove_leading_comments=False)
    # wc.add_attr(None, 'PrivateKey', 'XXXXXXXXXXXXXXXXXXXXXXXXXXX=')
    wc.write_file()

def removeAttrFail():
    wc = wgconfig.WGConfig('./wg0.conf')
    wc.read_file()
    print(wc.interface)
    # wc.del_attr(None,'PrivateKey')
    wc.del_attr(None,'ListenPort')
    # wc.add_attr(None, 'PrivateKey', 'XXXXXXXXXXXXXXXXXXXXXXXX=')
    wc.write_file()

removeAttr()
removeAttrFail()

**Comment by towalink** [comment]
Thanks for reporting this. It appears that blank lines before attributes are not handled properly. That exception should not occur at all. I will fix it.

**Comment by towalink** [comment]
Fixed in https://github.com/towalink/wgconfig/commit/2718ac20c3e3984352f118d2b81fa4d1261725b1
Published release v0.2.3 incl. this.
