### ISSUE TITLE
Documenting how it deals with multiple Address lines in the interface section

### ISSUE THREAD

**Issue by OtherSystems** [towalink/wgconfig#6]
At the moment it's unclear how the module deals with multiple Address lines in the Interface section in case there is a IPv4 and IPv6 address. It seems like keys should be unique in the [Interface] section which wouldn't match with what is allowed and exists in realworld scenarios.

**Comment by towalink** [comment]
Thanks for your note! It is usual to state IPv4 address and IPv6 address in a single line, e.g. "Address = 192.168.1.1/32, fd00::10:10/128". However, you're right that multiple keys with the same name are allowed in WireGuard config files, e.g. for "AllowedIPs". Thus, wgconfig should be able to deal with such cases properly. I will look into it.

**Comment by towalink** [comment]
The documentation got improved considerably. The handling of attributes with the same name should become clear now. There is also a new "documentation" folder with an additional example.
