### ISSUE TITLE
Documentation about wg-tools needing to be installed for wgexec.py

### ISSUE THREAD

**Issue by elreydetoda** [towalink/wgconfig#7]
I wanted to check before doing a PR for documentation, but I don't believe there's any docs about needing the wg-tools (which isn't necessarily required to run wireguard since it's integrated into Linux kernels) to be installed for using wgexec.py.

While _I_ know, and most people will know, it might not hurt to have it explicitly called out.

Do you have any preference for the specific location to call that out if I was to do a PR for this project? (that is if you're accepting PRs).

**Comment by towalink** [comment]
Thanks for this improvement suggestion!
I added some info in the FileNotFound exception to give a more explicit reason and to point out how to resolve it. This is commit e5537bff1174bc33591d0fff7f8287b592221eda. I also added a little note in README.md (but nothing distribution-specific).

**Comment by elreydetoda** [comment]
Awesome, thank you!
